export const continents = [
  {
    id: 1,
    name: 'América do Norte',
    slogan: 'América para o mundo',
    image: 'img/north_america.png',
    route: 'north_america',
    details: {
      image: 'img/north_america_continent.png',
      resume:
        'A América do Norte é um subcontinente que compreende a porção setentrional do continente americano. Existem duas formas de classificar esse continente: a primeira considera que a América do Norte é apenas a parte mais setentrional da América, separada da América Central na fronteira entre o México e a Guatemala, a segunda classificação reconhece apenas uma América do Norte e uma América do Sul.',
      countries: 3,
      languages: 6,
      citiesTop100: 10,
      citiesTop5: [
        {
          rank: 8,
          image: 'img/card/new_york_city.png',
          city: 'Nova York',
          country: 'Estados Unidos',
          flag: 'img/card/flag/us.png',
        },
        {
          rank: 27,
          image: 'img/card/miami.png',
          city: 'Miami',
          country: 'Estados Unidos',
          flag: 'img/card/flag/us.png',
        },
        {
          rank: 29,
          image: 'img/card/los_angeles.png',
          city: 'Los Angeles',
          country: 'Estados Unidos',
          flag: 'img/card/flag/us.png',
        },
        {
          rank: 34,
          image: 'img/card/las_vegas.png',
          city: 'Las Vegas',
          country: 'Estados Unidos',
          flag: 'img/card/flag/us.png',
        },
        {
          rank: 40,
          image: 'img/card/cancun.png',
          city: 'Cancún',
          country: 'México',
          flag: 'img/card/flag/mexico.png',
        },
      ],
    },
  },
  {
    id: 2,
    name: 'América do Sul',
    slogan: 'Alegria, cultura e natureza',
    image: 'img/south_america.png',
    route: 'south_america',
    details: {
      image: '',
      resume:
        'A América do Sul é um continente que compreende a porção meridional da América. Une-se à América Central a norte pelo istmo do Panamá e se separa da Antártida ao sul pelo estreito de Drake. Os outros pontos extremos da América do Sul são: ao norte a Punta Gallinas, na Colômbia, ao leste a Ponta do Seixas, no Brasil, e a oeste a Punta Pariñas, no Peru.',
      countries: 12,
      languages: 9,
      citiesTop100: 3,
      citiesTop5: [
        {
          rank: 85,
          image: 'img/card/buenos_aires.png',
          city: 'Buenos Aires',
          country: 'Argentina',
          flag: 'img/card/flag/argentina.png',
        },
        {
          rank: 89,
          image: 'img/card/lima.png',
          city: 'Lima',
          country: 'Peru',
          flag: 'img/card/flag/peru.png',
        },
        {
          rank: 98,
          image: 'img/card/rio_de_janeiro.png',
          city: 'Rio de Janeiro',
          country: 'Brasil',
          flag: 'img/card/flag/brazil.png',
        },
      ],
    },
  },
  {
    id: 3,
    name: 'Ásia',
    slogan: 'A diversidade do maior dos contineites',
    image: 'img/asian.png',
    route: 'asian',
    details: {
      image: 'img/asia_continent',
      resume:
        'A Ásia é o maior dos continentes, tanto em área como em população. Abrange um terço das partes sólidas da superfície da Terra e é responsável por abrigar quase três quintos da população mundial. A Ásia faz fronteira no lado ocidental com a África e com a Europa, e no lado oriental com o oceano Pacífico, a Oceania e, em menor proporção, com a América do Norte, pelo Estreito de Bering.',
      countries: 50,
      languages: 7,
      citiesTop100: 43,
      citiesTop5: [
        {
          rank: 1,
          image: 'img/card/hong_kong.png',
          city: 'Hong Kong',
          country: 'China',
          flag: 'img/card/flag/china.png',
        },
        {
          rank: 2,
          image: 'img/card/bangkok.png',
          city: 'Bancoque',
          country: 'Tailândia',
          flag: 'img/card/flag/thailand.png',
        },
        {
          rank: 4,
          image: 'img/card/macau.png',
          city: 'Macau',
          country: 'China',
          flag: 'img/card/flag/china.png',
        },
        {
          rank: 5,
          image: 'img/card/singapore.png',
          city: 'Singapura',
          country: 'Singapura',
          flag: 'img/card/flag/singapore.png',
        },
        {
          rank: 9,
          image: 'img/card/kuala_lumpur.png',
          city: 'Kuala Lumpur',
          country: 'Malásia',
          flag: 'img/card/flag/malaysia.png',
        },
      ],
    },
  },
  {
    id: 4,
    name: 'África',
    slogan: 'Os mistérios do berço da humnidade',
    image: 'img/africa.png',
    route: 'africa',
    details: {
      image: '',
      resume:
        'A África é o terceiro continente mais extenso (depois da Ásia e da América). Apresenta grande diversidade étnica, cultural, social e política. Dos trinta países mais pobres do mundo (com mais problemas de subnutrição, analfabetismo, baixa expectativa de vida), pelo menos 21 são africanos. Apesar disso existem alguns países com um padrão de vida razoável, mas não existe nenhum país realmente desenvolvido na África.',
      countries: 54,
      languages: 3000,
      citiesTop100: 4,
      citiesTop5: [
        {
          rank: 42,
          image: 'img/card/cairo.png',
          city: 'Cairo',
          country: 'Egito',
          flag: 'img/card/flag/egypt.png',
        },
        {
          rank: 54,
          image: 'img/card/johannesburg.png',
          city: 'Joanesburgo',
          country: 'África do Sul',
          flag: 'img/card/flag/south_africa.png',
        },
        {
          rank: 75,
          image: 'img/card/marrakech.png',
          city: 'Marraquexe',
          country: 'Marrocos',
          flag: 'img/card/flag/morocco.png',
        },
        {
          rank: 82,
          image: 'img/card/hurghada.png',
          city: 'Hurghada',
          country: 'Egito',
          flag: 'img/card/flag/egypt.png',
        },
      ],
    },
  },
  {
    id: 5,
    name: 'Europa',
    slogan: 'O contineite mais antigo',
    image: 'img/europe.png',
    route: 'europe',
    details: {
      image: 'img/europe_continent.png',
      resume:
        'A Europa é, por convenção, um dos seis continentes do mundo. Compreendendo a península ocidental da Eurásia, a Europa geralmente divide-se da Ásia a leste pela divisória de águas dos montes Urais, o rio Ural, o mar Cáspio, o Cáucaso, e o mar Negro a sudeste',
      countries: 50,
      languages: 60,
      citiesTop100: 32,
      citiesTop5: [
        {
          rank: 3,
          image: 'img/card/london.png',
          city: 'Londres',
          country: 'Reino Unido',
          flag: 'img/card/flag/united_kingdom.png',
        },
        {
          rank: 6,
          image: 'img/card/paris.png',
          city: 'Paris',
          country: 'França',
          flag: 'img/card/flag/france.png',
        },
        {
          rank: 16,
          image: 'img/card/rome.png',
          city: 'Roma',
          country: 'Itália',
          flag: 'img/card/flag/italy.png',
        },
        {
          rank: 22,
          image: 'img/card/prague.png',
          city: 'Praga',
          country: 'República Tcheca',
          flag: 'img/card/flag/czech_republic.png',
        },
        {
          rank: 25,
          image: 'img/card/amsterdam.png',
          city: 'Amsterdã',
          country: 'Holanda',
          flag: 'img/card/flag/netherlands.png',
        },
      ],
    },
  },
  {
    id: 6,
    name: 'Oceania',
    slogan: 'O menor e mais novo dos continentes',
    image: 'img/oceania.png',
    route: 'oceania',
    details: {
      image: 'img/oceania_continent.png',
      resume:
        'Oceania ou Oceânia é uma região geográfica composta por vários grupos de ilhas do oceano Pacífico (Polinésia, Melanésia e Micronésia). O termo Oceania foi criado em 1831 pelo explorador francês Dumont d`Urville. O termo é usado hoje em vários idiomas para designar uma região geográfica e política que compreende o continente da Austrália e ilhas do Oceano Pacífico adjacentes.',
      countries: 16,
      languages: 18,
      citiesTop100: 8,
      citiesTop5: [
        {
          rank: 32,
          image: 'img/card/denpasar.png',
          city: 'Denpasar',
          country: 'Indonésia',
          flag: 'img/card/flag/indonesia.png',
        },
        {
          rank: 55,
          image: 'img/card/sydney.png',
          city: 'Sydney',
          country: 'Autrália',
          flag: 'img/card/flag/australia.png',
        },
        {
          rank: 57,
          image: 'img/card/jakarta.png',
          city: 'Jacarta',
          country: 'Indonésia',
          flag: 'img/card/flag/indonesia.png',
        },
        {
          rank: 73,
          image: 'img/card/melbourne.png',
          city: 'Melbourne',
          country: 'Autrália',
          flag: 'img/card/flag/australia.png',
        },

        {
          rank: 78,
          image: 'img/card/auckland.png',
          city: 'Auckland',
          country: 'Nova Zelândia',
          flag: 'img/card/flag/new_zealand.png',
        },
      ],
    },
  },
];
